<?php
/**
 * User: zura
 * Date: 2/26/19
 * Time: 2:28 PM
 */

namespace intermundia\yiicms\widgets;


use intermundia\yiicms\models\Language;
use yii\bootstrap\Dropdown;
use yii\helpers\ArrayHelper;

/**
 * Class LanguagePicker
 *
 * @author Zura Sekhniashvili <zurasekhniashvili@gmail.com>
 * @package intermundia\yiicms\widgets
 */
class LanguagePicker extends Dropdown
{
    public function init()
    {
        $this->items = array_map(function ($lang) {
            /** @var Language $lang */
            return [
                'label' => $lang->name,
                'url' => ['/site/set-locale', 'locale' => $lang->code]
            ];
        }, Language::find()->all());
        parent::init();
    }

    public function run()
    {
        return parent::run(); // TODO: Change the autogenerated stub
    }
}